//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrDax.RadioClient {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Pēdējā atskaņotā kanāla identifikators, piemēram, retro.3
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Pēdējā atskaņotā kanāla identifikators, piemēram, retro.3")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ChannelId {
            get {
                return ((string)(this["ChannelId"]));
            }
            set {
                this["ChannelId"] = value;
            }
        }
        
        /// <summary>
        /// Skaļums no 0 (pilnīgs klusums) līdz 1 (maksimums).
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Skaļums no 0 (pilnīgs klusums) līdz 1 (maksimums).")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Volume {
            get {
                return ((double)(this["Volume"]));
            }
            set {
                this["Volume"] = value;
            }
        }
        
        /// <summary>
        /// Vai atslēgt skaņu, kad lietotājs bloķē darbstaciju.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Vai atslēgt skaņu, kad lietotājs bloķē darbstaciju.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MuteOnLock {
            get {
                return ((bool)(this["MuteOnLock"]));
            }
            set {
                this["MuteOnLock"] = value;
            }
        }
        
        /// <summary>
        /// Kanālu identifikatori, kurus nerāda pārslēgšanas sarakstā. Atdalīti ar tukšumu.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Kanālu identifikatori, kurus nerāda pārslēgšanas sarakstā. Atdalīti ar tukšumu.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IgnoredChannels {
            get {
                return ((string)(this["IgnoredChannels"]));
            }
            set {
                this["IgnoredChannels"] = value;
            }
        }
        
        /// <summary>
        /// Vai HTTP kanālam un raidījumu sarakstu izgūšanai jālieto sistēmā noteiktais proksi (tas pats, kuru lieto Internet Explorer).
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Vai HTTP kanālam un raidījumu sarakstu izgūšanai jālieto sistēmā noteiktais starpniekserveris (tas pats, kuru izmanto Internet Explorer).")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSystemProxy {
            get {
                return ((bool)(this["UseSystemProxy"]));
            }
            set {
                this["UseSystemProxy"] = value;
            }
        }
        
        /// <summary>
        /// Vai izgūt un attēlot raidījumu sarakstu.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Vai izgūt un attēlot raidījumu sarakstu.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseGuide {
            get {
                return ((bool)(this["UseGuide"]));
            }
            set {
                this["UseGuide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Configuration.SettingsDescriptionAttribute("Vai rādīt laiku studijā.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClock {
            get {
                return ((bool)(this["ShowClock"]));
            }
            set {
                this["ShowClock"] = value;
            }
        }
    }
}
